defaults:
    - _self_

wandb_project: vlmflow
wandb_entity: avagr
seed: 57

disable_wandb: true
disable_tqdm: false
resume_wandb_id: null
max_workers: 16

results_dir: /home/projects/shimon/agroskin/projects/vlmflow/results
run_dir: Unlabeled_COCO/llava_3000_2024_09_26-02_13_31
#run_dir: Unlabeled_COCO/llava_test_2024_09_16-00_10_20

construct_graphs: false
graph_threshold: 0.02

# Vertex metrics
modality_contribution: false
modality_centrality: false
local_clustering_coefficient: false

# Graph metrics
graph_density: false
node_edge_densities: true
cross_modal_edges: ${modality_contribution}
global_clustering_coefficient: false
residual_stream_heights: false
centrality_overlap: ${modality_centrality}
