defaults:
    - _self_
    - model: llava

wandb_project: vlmflow
wandb_entity: avagr
seed: 57

disable_wandb: true
disable_tqdm: false
resume_wandb_id: null
max_workers: 16

results_dir: /home/projects/shimon/agroskin/projects/vlmflow/results
run_dir: Unlabeled_COCO/llava_2000_2024_09_15-01_57_15/

graph_threshold: 0.02

# Vertex metrics
modality_contribution: true
modality_centrality: true
clustering_coefficient: true

# Graph metrics
graph_density: true
num_cross_modal_edges: true
