defaults:
    - _self_
    - model: molmo

wandb_project: vlmflow
wandb_entity: avagr
seed: 57

disable_wandb: true
disable_tqdm: false
resume_wandb_id: null
max_workers: 16

results_dir: /home/projects/shimon/agroskin/projects/vlmflow/results
run_dir: Unlabeled_COCO/molmo_72b_merged_600
#run_dir: Unlabeled_COCO/llava_test_2024_09_16-00_10_20

construct_graphs: true
graph_threshold: 0.01

# Vertex metrics
modality_contribution: true
modality_centrality: true
local_clustering_coefficient: true

# Graph metrics
graph_density: true
cross_modal_edges: ${modality_contribution}
global_clustering_coefficient: true
residual_stream_heights: true
centrality_overlap: ${modality_centrality}
